# Site settings
title: "Arthur Cunha"
email: arthuromcunha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://artcunha.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username: artcunha 
linkedin_username: artcunha
vimeo_username: artcunha
instagram_username: artcunha.om
artstation_username: artcunha

# Build settings
markdown: kramdown
permalink: pretty
